<a href="https://colab.research.google.com/github/Sjinjutha/DADS7202-DL/blob/main/DADS7202_HW01_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import pandas as pd
import numpy as np

In [3]:
data = pd.read_csv("/content/drive/MyDrive/data_travel_insurance.csv")
data

Unnamed: 0 Agency  Agency Type  Distribution Channel  Duration  \
0               0    CBH            0                     0       186   
1               1    CBH            0                     0       186   
2               2    CWT            0                     1        65   
3               3    CWT            0                     1        60   
4               4    CWT            0                     1        79   
...           ...    ...          ...                   ...       ...   
62337       63321    JZI            1                     1       111   
62338       63322    JZI            1                     1        58   
62339       63323    JZI            1                     1         2   
62340       63324    JZI            1                     1         3   
62341       63325    JZI            1                     1        22   

       Net Sales  Commision (in value)   Age  Claim  Des_Singapore  ...  \
0          -29.0                  9.57  81.0      0              0  ...   
1          -29.0                  9.57  71.0      0              0  ...   
2          -49.5                 29.70  32.0      0              0  ...   
3          -39.6                 23.76  32.0      0              0  ...   
4          -19.8                 11.88  41.0      0              0  ...   
...          ...                   ...   ...    ...            ...  ...   
62337       35.0                 12.25  31.0      0              0  ...   
62338       40.0                 14.00  40.0      0              0  ...   
62339       18.0                  6.30  57.0      0              0  ...   
62340       18.0                  6.30  63.0      0              0  ...   
62341       26.0                  9.10  35.0      0              0  ...   

       Destination_UNITED KINGDOM  Destination_UNITED STATES  \
0                               0                          0   
1                               0                          0   
2                               0                          0   
3                               0                          0   
4                               0                          0   
...                           ...                        ...   
62337                           0                          0   
62338                           0                          0   
62339                           0                          0   
62340                           0                          0   
62341                           0                          0   

       Destination_URUGUAY  Destination_UZBEKISTAN  Destination_VANUATU  \
0                        0                       0                    0   
1                        0                       0                    0   
2                        0                       0                    0   
3                        0                       0                    0   
4                        0                       0                    0   
...                    ...                     ...                  ...   
62337                    0                       0                    0   
62338                    0                       0                    0   
62339                    0                       0                    0   
62340                    0                       0                    0   
62341                    0                       0                    0   

       Destination_VENEZUELA  Destination_VIET NAM  \
0                          0                     0   
1                          0                     0   
2                          0                     0   
3                          0                     0   
4                          0                     0   
...                      ...                   ...   
62337                      0                     0   
62338                      0                     0   
62339                      0                     0   
62340              

In [4]:
data.drop('Unnamed: 0', axis=1, inplace=True)
data.drop('Destination_SINGAPORE', axis=1, inplace=True)
data.drop('Agency', axis=1, inplace=True)
data

Agency Type  Distribution Channel  Duration  Net Sales  \
0                0                     0       186      -29.0   
1                0                     0       186      -29.0   
2                0                     1        65      -49.5   
3                0                     1        60      -39.6   
4                0                     1        79      -19.8   
...            ...                   ...       ...        ...   
62337            1                     1       111       35.0   
62338            1                     1        58       40.0   
62339            1                     1         2       18.0   
62340            1                     1         3       18.0   
62341            1                     1        22       26.0   

       Commision (in value)   Age  Claim  Des_Singapore  \
0                      9.57  81.0      0              0   
1                      9.57  71.0      0              0   
2                     29.70  32.0      0              0   
3                     23.76  32.0      0              0   
4                     11.88  41.0      0              0   
...                     ...   ...    ...            ...   
62337                 12.25  31.0      0              0   
62338                 14.00  40.0      0              0   
62339                  6.30  57.0      0              0   
62340                  6.30  63.0      0              0   
62341                  9.10  35.0      0              0   

       Product Name_1 way Comprehensive Plan  \
0                                          0   
1                                          0   
2                                          0   
3                                          0   
4                                          0   
...                                      ...   
62337                                      0   
62338                                      0   
62339                                      0   
62340                                      0   
62341                                      0   

       Product Name_2 way Comprehensive Plan  ...  Destination_UNITED KINGDOM  \
0                                          0  ...                           0   
1                                          0  ...                           0   
2                                          0  ...                           0   
3                                          0  ...                           0   
4                                          0  ...                           0   
...                                      ...  ...                         ...   
62337                                      0  ...                           0   
62338                                      0  ...                           0   
62339                                      0  ...                           0   
62340                                      0  ...                           0   
62341                                      0  ...                           0   

       Destination_UNITED STATES  Destination_URUGUAY  Destination_UZBEKISTAN  \
0                              0                    0                       0   
1                              0                    0                       0   
2                              0                    0                       0   
3                              0                    0                       0   
4                              0                    0                       0   
...                          ...                  ...                     ...   
62337                          0                    0                       0   
62338                          0                    0                       0   
62339                          0                    0                       0   
62340                          0                    0                       0   
62341                          0                    0                       

In [5]:
Y = pd.DataFrame(data.loc[:,'Claim'], columns=['Claim'])

data.drop('Claim', axis=1, inplace=True)
X = data

In [6]:
from sklearn.preprocessing import StandardScaler

In [7]:
scaler = StandardScaler()
scaler.fit(X.loc[:,"Duration":"Age"])
X_scale = scaler.transform(X.loc[:,"Duration":"Age"])
X.loc[:,"Duration":"Age"] = X_scale

In [8]:
X

Agency Type  Distribution Channel  Duration  Net Sales  \
0                0                     0  1.330803  -1.422986   
1                0                     0  1.330803  -1.422986   
2                0                     1  0.149913  -1.842353   
3                0                     1  0.101116  -1.639829   
4                0                     1  0.286545  -1.234782   
...            ...                   ...       ...        ...   
62337            1                     1  0.598847  -0.113741   
62338            1                     1  0.081597  -0.011456   
62339            1                     1 -0.464930  -0.461509   
62340            1                     1 -0.455171  -0.461509   
62341            1                     1 -0.269742  -0.297854   

       Commision (in value)       Age  Des_Singapore  \
0                 -0.004645  4.185459              0   
1                 -0.004645  3.195091              0   
2                  1.011775 -0.667346              0   
3                  0.711848 -0.667346              0   
4                  0.111993  0.223985              0   
...                     ...       ...            ...   
62337              0.130675 -0.766383              0   
62338              0.219038  0.124949              0   
62339             -0.169757  1.808575              0   
62340             -0.169757  2.402796              0   
62341             -0.028377 -0.370236              0   

       Product Name_1 way Comprehensive Plan  \
0                                          0   
1                                          0   
2                                          0   
3                                          0   
4                                          0   
...                                      ...   
62337                                      0   
62338                                      0   
62339                                      0   
62340                                      0   
62341                                      0   

       Product Name_2 way Comprehensive Plan  Product Name_24 Protect  ...  \
0                                          0                        0  ...   
1                                          0                        0  ...   
2                                          0                        0  ...   
3                                          0                        0  ...   
4                                          0                        0  ...   
...                                      ...                      ...  ...   
62337                                      0                        0  ...   
62338                                      0                        0  ...   
62339                                      0                        0  ...   
62340                                      0                        0  ...   
62341                                      0                        0  ...   

       Destination_UNITED KINGDOM  Destination_UNITED STATES  \
0                               0                          0   
1                               0                          0   
2                               0                          0   
3                               0                          0   
4                               0                          0   
...                           ...                        ...   
62337                           0                          0   
62338                           0                          0   
62339                           0                          0   
62340                           0                          0   
62341                           0                          0   

       Destination_URUGUAY  Destination_UZBEKISTAN  Destination_VANUATU  \
0                        0                       0                    0   
1                        0                       0                    0   
2                        0                   

### Imbalanced Dataset

In [9]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from xgboost.sklearn import XGBClassifier
from imblearn.under_sampling import InstanceHardnessThreshold

from sklearn.model_selection import GridSearchCV, RandomizedSearchCV
from sklearn.metrics import f1_score, roc_auc_score, recall_score, precision_score, confusion_matrix, classification_report

In [10]:
claim = pd.DataFrame(Y.groupby(["Claim"]).size(), columns=['Frequency'])
claim['Percent'] = round((claim['Frequency'] / Y.shape[0])*100 , 2)
claim

Frequency  Percent
Claim                    
0          61425    98.53
1            917     1.47

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42, stratify=Y)

In [12]:
values = []
models = [ RandomForestClassifier(), LogisticRegression(), DecisionTreeClassifier(), SVC(), KNeighborsClassifier(), XGBClassifier()]
for m in models:
  m.fit(X_train, y_train)
  y_pred = m.predict(X_test)
  print(m)
  
  print(classification_report(y_test,y_pred)[1])
  print(confusion_matrix(y_test,y_pred))
  values.append([str(m)[:10], f1_score(y_test,y_pred), roc_auc_score(y_test,y_pred), recall_score(y_test,y_pred), precision_score(y_test,y_pred)])
  print('='*60)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  after removing the cwd from sys.path.


RandomForestClassifier()
 
[[12252    34]
 [  178     5]]


/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


LogisticRegression()
 
[[12285     1]
 [  183     0]]
DecisionTreeClassifier()
 
[[12064   222]
 [  173    10]]


/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC()
 
[[12286     0]
 [  183     0]]


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classificat

KNeighborsClassifier()
 
[[12279     7]
 [  183     0]]


/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_label.py:98: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_label.py:133: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


XGBClassifier()
 
[[12286     0]
 [  183     0]]


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classificat

In [13]:
values.insert(0,['Model','f1_score','roc_auc_score','recall_score','precision_score'])
results = pd.DataFrame(values[1:], columns=values[0])
results

Model  f1_score  roc_auc_score  recall_score  precision_score
0  RandomFore  0.045045       0.512278      0.027322         0.128205
1  LogisticRe  0.000000       0.499959      0.000000         0.000000
2  DecisionTr  0.048193       0.518288      0.054645         0.043103
3       SVC()  0.000000       0.500000      0.000000         0.000000
4  KNeighbors  0.000000       0.499715      0.000000         0.000000
5  XGBClassif  0.000000       0.500000      0.000000         0.000000

In [14]:
iht = InstanceHardnessThreshold(random_state=42)
X_res, Y_res = iht.fit_resample(X, Y)

In [15]:
claim_res = pd.DataFrame(Y_res.groupby(["Claim"]).size(), columns=['Frequency'])
claim_res['Percent'] = round((claim_res['Frequency'] / Y_res.shape[0])*100 , 2)
claim_res

Frequency  Percent
Claim                    
0          48797    98.16
1            917     1.84

In [16]:
X_res_train, X_res_test, y_res_train, y_res_test = train_test_split(X_res, Y_res, test_size=0.2, random_state=42, stratify=Y_res)

In [17]:
values = []
models = [ RandomForestClassifier(), LogisticRegression(), DecisionTreeClassifier(random_state=42), SVC(), KNeighborsClassifier(), XGBClassifier()]
for m in models:
  m.fit(X_res_train, y_res_train)
  y_res_pred = m.predict(X_res_test)
  print(m)
  print(classification_report(y_res_test, y_res_pred)[1])
  print(confusion_matrix(y_res_test, y_res_pred))
  values.append([str(m)[:10], f1_score(y_res_test,y_res_pred), roc_auc_score(y_res_test,y_res_pred), recall_score(y_res_test,y_res_pred), precision_score(y_res_test,y_res_pred)])
  print('='*60)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  after removing the cwd from sys.path.


RandomForestClassifier()
 
[[9731   29]
 [ 121   62]]


/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


LogisticRegression()
 
[[9753    7]
 [ 173   10]]
DecisionTreeClassifier(random_state=42)
 
[[9662   98]
 [ 109   74]]


/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC()
 
[[9753    7]
 [ 167   16]]


/usr/local/lib/python3.7/dist-packages/sklearn/neighbors/_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier()
 
[[9732   28]
 [ 145   38]]


/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_label.py:98: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_label.py:133: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


XGBClassifier()
 
[[9745   15]
 [ 162   21]]


In [18]:
values.insert(0,['Model','f1_score','roc_auc_score','recall_score','precision_score'])
results = pd.DataFrame(values[1:],columns=values[0])
results

## คะแนนโดยรวมหลังจากที่มีการทำ Imbalanced (InstanceHardnessThreshold) ให้ผลดีกว่า
## เลือก RandomForest model มาปรับ tune ต่อเนื่องจากให้ค่า f1-score สูง

Model  f1_score  roc_auc_score  recall_score  precision_score
0  RandomFore  0.452555       0.667913      0.338798         0.681319
1  LogisticRe  0.100000       0.526964      0.054645         0.588235
2  DecisionTr  0.416901       0.697165      0.404372         0.430233
3       SVC()  0.155340       0.543357      0.087432         0.695652
4  KNeighbors  0.305221       0.602391      0.207650         0.575758
5  XGBClassif  0.191781       0.556609      0.114754         0.583333

# Feature Selection with RandomForests

In [19]:
from sklearn.feature_selection import SelectFromModel

In [20]:
sel = SelectFromModel(RandomForestClassifier())
sel.fit(X_res_train, y_res_train)

sel.get_support()

/usr/local/lib/python3.7/dist-packages/sklearn/feature_selection/_from_model.py:267: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  self.estimator_.fit(X, y, **fit_params)


array([ True, False,  True,  True,  True,  True,  True, False, False,
       False, False,  True, False, False, False, False,  True, False,
       False, False, False, False, False, False,  True, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,

In [21]:
selected_feat = X_res_train.columns[(sel.get_support())]
print(selected_feat)
len(selected_feat)

Index(['Agency Type', 'Duration', 'Net Sales', 'Commision (in value)', 'Age',
       'Des_Singapore', 'Product Name_Annual Silver Plan',
       'Product Name_Bronze Plan', 'Product Name_Silver Plan'],
      dtype='object')


9

In [22]:
X_train_selected = X_res_train.loc[:,selected_feat]
X_train_selected

Agency Type  Duration  Net Sales  Commision (in value)       Age  \
33717            0 -0.133110   0.152199             -0.487861 -0.271199   
23689            0 -0.328299   0.929563              1.162244 -1.657715   
43666            0 -0.377096  -0.625165             -0.487861 -0.271199   
27555            1 -0.152629  -0.594479             -0.342442  0.719170   
29913            1 -0.367336  -0.522880             -0.184905  1.808575   
...            ...       ...        ...                   ...       ...   
28286            0 -0.406374  -0.625165             -0.487861 -0.271199   
4522             0  0.013281  -0.543337             -0.487861 -0.271199   
35244            1 -0.220945  -0.297854             -0.028377 -1.360604   
30372            0 -0.367336  -0.154655              0.145318  0.917243   
19592            1 -0.435652  -0.733587             -0.404548  0.917243   

       Des_Singapore  Product Name_Annual Silver Plan  \
33717              1                                0   
23689              0                                0   
43666              0                                0   
27555              1                                0   
29913              0                                0   
...              ...                              ...   
28286              0                                0   
4522               0                                0   
35244              0                                0   
30372              0                                0   
19592              1                                0   

       Product Name_Bronze Plan  Product Name_Silver Plan  
33717                         0                         0  
23689                         0                         0  
43666                         0                         0  
27555                         1                         0  
29913                         0                         0  
...                         ...                       ...  
28286                         0                         0  
4522                          0                         0  
35244                         0                         0  
30372                         0                         0  
19592                         0                         0  

[39771 rows x 9 columns]

In [23]:
X_test_selected = X_res_test.loc[:,selected_feat]
X_test_selected

Agency Type  Duration  Net Sales  Commision (in value)       Age  \
15128            0 -0.357577   0.806821             -0.487861 -0.271199   
45378            0 -0.386855  -0.236483             -0.487861 -0.370236   
26345            1 -0.445412  -0.451281             -0.254080 -0.766383   
46126            0 -0.015997  -0.625165             -0.487861 -0.370236   
43194            1 -0.416133  -0.369453             -0.203587 -1.063494   
...            ...       ...        ...                   ...       ...   
37259            0  0.315823  -0.154655             -0.487861 -0.271199   
37841            0  0.276786  -0.093284             -0.487861 -0.271199   
23852            0  0.003522  -0.604708             -0.487861 -0.271199   
25235            1 -0.113591  -0.297854             -0.028377  0.223985   
10973            0 -0.318539  -0.424687              0.111993 -0.271199   

       Des_Singapore  Product Name_Annual Silver Plan  \
15128              0                                0   
45378              0                                0   
26345              1                                0   
46126              0                                0   
43194              1                                0   
...              ...                              ...   
37259              0                                0   
37841              0                                0   
23852              0                                0   
25235              0                                0   
10973              0                                0   

       Product Name_Bronze Plan  Product Name_Silver Plan  
15128                         0                         0  
45378                         0                         0  
26345                         0                         1  
46126                         0                         0  
43194                         0                         1  
...                         ...                       ...  
37259                         0                         0  
37841                         0                         0  
23852                         0                         0  
25235                         0                         0  
10973                         0                         0  

[9943 rows x 9 columns]

# Tune Hyperparameter

In [ ]:
# use GridSerchCV to find the best parameter by exhaustive search over specified parameter values for an estimator.

from sklearn.model_selection import GridSearchCV

clf = RandomForestClassifier(random_state=42)

# defining parameter range
param_grid = {'criterion':['gini','entropy','log_loss'],
              'max_depth':[int(x) for x in range(2,21,1)],
              'max_features':['sqrt','log2'],
              'class_weight':['balanced','balanced_subsample',None]
              }

grid = GridSearchCV(clf, param_grid, cv=10, scoring='f1', return_train_score=True, verbose=1)
  
# fitting the model for grid search
grid_search = grid.fit(X_train_selected, y_res_train)

print(grid_search.best_params_)

Fitting 10 folds for each of 342 candidates, totalling 3420 fits


Streaming output truncated to the last 5000 lines.
/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py:680: DataConv

{'class_weight': 'balanced', 'criterion': 'entropy', 'max_depth': 14, 'max_features': 'sqrt'}


In [ ]:
# {'class_weight': 'balanced', 'criterion': 'entropy', 'max_depth': 15, 'max_features': 'sqrt'}

In [24]:
rf = RandomForestClassifier(class_weight='balanced', criterion='entropy', max_depth=14, random_state=42)

rf.fit(X_train_selected, y_res_train)
y_selected_pred = rf.predict(X_test_selected)
  
print(classification_report(y_res_test, y_selected_pred)[1])
print(confusion_matrix(y_res_test, y_selected_pred))

values = []
values.append([str(rf)[:10], f1_score(y_res_test,y_selected_pred), roc_auc_score(y_res_test,y_selected_pred), 
               recall_score(y_res_test,y_selected_pred), precision_score(y_res_test,y_selected_pred)])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


 
[[9639  121]
 [  98   85]]


In [25]:
values.insert(0,['Model','f1_score','roc_auc_score','recall_score','precision_score'])
results = pd.DataFrame(values[1:], columns=values[0])
results

Model  f1_score  roc_auc_score  recall_score  precision_score
0  RandomFore  0.437018       0.726042      0.464481         0.412621